# Generated by Django 4.2.4 on 2023-11-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_driver_email_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='per_day',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_fare',
            field=models.FloatField(default=2000),
        ),
    ]
