# Generated by Django 4.1.2 on 2023-11-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_vehicle_per_day_vehicle_min_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='per_day',
            field=models.FloatField(default=8000),
        ),
    ]
